// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjclvjxpufulxinxmnul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqY2x2anhwdWZ1bHhpbnhtbnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDgyODEsImV4cCI6MjA2ODg4NDI4MX0.RVwNL4dBPEPhvXjfZnIR3RWMI3u-pSSe9F7G-Lzl5rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});