// This file is automatically generated by Lovable.
// NOTE: We DO customize the auth storage adapter here to support Capacitor (native).
import { createClient } from '@supabase/supabase-js';
import type { SupportedStorage } from '@supabase/auth-js';
import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';
import type { Database } from './types';

const SUPABASE_URL = "https://hjclvjxpufulxinxmnul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqY2x2anhwdWZ1bHhpbnhtbnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDgyODEsImV4cCI6MjA2ODg4NDI4MX0.RVwNL4dBPEPhvXjfZnIR3RWMI3u-pSSe9F7G-Lzl5rs";

const capacitorStorage: SupportedStorage = {
  async getItem(key: string) {
    const { value } = await Preferences.get({ key });
    return value ?? null;
  },
  async setItem(key: string, value: string) {
    await Preferences.set({ key, value });
  },
  async removeItem(key: string) {
    await Preferences.remove({ key });
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: Capacitor.isNativePlatform() ? capacitorStorage : localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
  },
});
